//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectEstimate
    {
        public int id { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> MaterialQuantity { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> EquipmentQuantity { get; set; }
    
        public virtual equipment equipment { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Project Project { get; set; }
    }
}
